- Cargo.toml
- README.rst
- src/bin/snd-fireworks-ctl-service.rs
- src/efw.rs
- src/efw/clk_ctl.rs
- src/efw/guitar_ctl.rs
- src/efw/input_ctl.rs
- src/efw/meter_ctl.rs
- src/efw/mixer_ctl.rs
- src/efw/model.rs
- src/efw/output_ctl.rs
- src/efw/port_ctl.rs
- src/efw/transactions.rs
- src/efw/unit.rs
- src/lib.rs
Background
----------
The models with Fireworks board module are already supported by ALSA
fireworks driver for their isochronous packet stream functionality
and vendor-specific transaction. Although the driver allows userspace
applications to process PCM frames and MIDI messages in the packet
streaming, it doesn't support the other functionalities such as volume
control since it can be achieved by any usespace application which
executes ioctl(2) to ALSA hwdep character device for the transaction.
The service program is to satisfy the demand to control the models.
ALSA control applications can request the control by IPC to the service
program.
In detail of mechanism, please read README.rst in the repository[1].
You can see some illustrations.
How to build
-------------
The project depends …
> Add service programs for Fireworks board module

- src/dg00x/common_ctl.rs
- src/efw/clk_ctl.rs
- src/tascam/common_ctl.rs
The operation to change sampling rate or clock source is invalid during
packet streaming.
This commit locks kernel packet streaming before changing them, then
unlock after. During kernel packet streaming, error returns.
> dg00x/tascam/efw: lock kernel streaming during changing clock rate and source

- Cargo.toml
- README.rst
- src/bin/snd-firewire-motu-ctl-service.rs
- src/lib.rs
- src/motu.rs
- src/motu/audioexpress.rs
- src/motu/common_proto.rs
- src/motu/f828mk2.rs
- src/motu/f828mk3.rs
- src/motu/f8pre.rs
- src/motu/h4pre.rs
- src/motu/model.rs
- src/motu/traveler.rs
- src/motu/ultralite.rs
- src/motu/ultralite_mk3.rs
- src/motu/unit.rs
- src/motu/v2_clk_ctls.rs
- src/motu/v2_port_ctls.rs
- src/motu/v2_proto.rs
- src/motu/v3_clk_ctls.rs
- src/motu/v3_port_ctls.rs
- src/motu/v3_proto.rs
This patchset adds service program for devices in MOTU FireWire series.
The devices in MOTU FireWire series are categorized to three generations. The patchset supports the devices in second and third generation. The added service program allows ALSA control applications to operate for device features which are controlled by MOTU Audio Console, therefore the feature of CueMix is not supported yet.
> motu: add service program for devices in MOTU FireWire series

- README.rst
- src/ta1394.rs
- src/ta1394/amdtp.rs
- src/ta1394/audio.rs
- src/ta1394/ccm.rs
- src/ta1394/general.rs
- src/ta1394/stream_format.rs
1394 Trading Association defines AV/C transaction based on Function Control Protocol defined in IEC 61883-1. The association also defined many kind of command/response on the transaction. The series of specification is public in its [website](http://1394ta.org/specifications/).
This patchset adds support for the AV/C transaction and a part of command/response for devices supported by ALSA firewire stack, referring to below documents:
* AV/C Digital Interface Command Set General Specification Version 4.2 (September 1, 2004. TA Document 2004006)
* Audio and Music Data Transmission Protocol 2.3 (April 24, 2012. Document 2009013)
* AV/C Connection and Compatibility Management Specification 1.1 (March 19, 2003. TA Document 2002010)
* AV/C Audio Subunit Specification 1.0 (October 24, 2000. TA …
> ta1394: add support for AV/C transaction and some commands

- Cargo.toml
- README.rst
- src/bin/snd-oxfw-ctl-service.rs
- src/card_cntr.rs
- src/efw/clk_ctl.rs
- src/efw/port_ctl.rs
- src/lib.rs
- src/oxfw.rs
- src/oxfw/apogee_ctls.rs
- src/oxfw/apogee_model.rs
- src/oxfw/apogee_proto.rs
- src/oxfw/common_ctl.rs
- src/oxfw/common_model.rs
- src/oxfw/griffin_model.rs
- src/oxfw/lacie_model.rs
- src/oxfw/model.rs
- src/oxfw/tascam_model.rs
- src/oxfw/tascam_proto.rs
- src/oxfw/unit.rs
Oxford Semiconductor designs OXFW970/OXFW971 ASIC for audio applications in IEEE 1394 bus. ALSA oxfw driver supports models with the ASIC for their isochronous packet stream functionality. Although the driver allows userspace applications to process PCM frames and MIDI messages in the packet streaming, it doesn't support the other functionalities such as volume control since it can be achieved by any usespace application.
This patchset adds service program to satisfy the demand to control the models. ALSA control applications can request the control by IPC to the service program. The service program works as proxy to execute actual control.
> oxfw: add service program for devices based on OXFW970/OXFW971 ASIC

- Cargo.toml
- README.rst
- src/bebob.rs
- src/bebob/apogee.rs
- src/bebob/apogee/apogee_ctls.rs
- src/bebob/apogee/apogee_model.rs
- src/bebob/apogee/apogee_proto.rs
- src/bebob/behringer.rs
- src/bebob/behringer/firepower_model.rs
- src/bebob/common_ctls.rs
- src/bebob/extensions.rs
- src/bebob/maudio.rs
- src/bebob/maudio/audiophile_model.rs
- src/bebob/maudio/common_proto.rs
- src/bebob/maudio/fw410_model.rs
- src/bebob/maudio/normal_ctls.rs
- src/bebob/maudio/ozonic_model.rs
- src/bebob/maudio/profirelightbridge_model.rs
- src/bebob/maudio/solo_model.rs
- src/bebob/maudio/special_ctls.rs
- src/bebob/maudio/special_model.rs
- src/bebob/model.rs
- src/bebob/stanton.rs
- src/bebob/unit.rs
- src/bin/snd-bebob-ctl-service.rs
- src/lib.rs
- src/ta1394/stream_format.rs
ArchWave AG (formerly known as BridgeCo AG) designs DM1000/DM1100/DM1500 ASICs for its solution to audio and music unit on IEEE 1394 bus, named as "BridgeCo Enhancement Break Out Box (BeBoB)". The ASICs are widely used for many models from hardware vendors.
ALSA bebob driver supports models with the ASIC for their isochronous packet stream functionality. Although the driver allows userspace applications to process PCM frames and MIDI messages in the packet streaming, it doesn't support the other functionalities such as volume control since it can be achieved by any usespace application.
This patchset adds service program to satisfy the demand to control the models. ALSA control applications can request the control by IPC to the service program. The service program works as proxy to …
> bebob: add service program for devices based on DM1000/DM1100/DM1500 ASICs

- Cargo.toml
- libs/alsa-ctl-tlv-codec/Cargo.toml
- libs/alsa-ctl-tlv-codec/README.md
- libs/alsa-ctl-tlv-codec/src/bin/db-calculate.rs
- libs/alsa-ctl-tlv-codec/src/bin/tlv-decode.rs
- libs/alsa-ctl-tlv-codec/src/containers.rs
- libs/alsa-ctl-tlv-codec/src/items.rs
- libs/alsa-ctl-tlv-codec/src/lib.rs
- libs/alsa-ctl-tlv-codec/src/range_utils.rs
- libs/alsa-ctl-tlv-codec/src/uapi.rs
- libs/bebob/Cargo.toml
- libs/bebob/src/apogee/apogee_ctls.rs
- libs/bebob/src/maudio/normal_ctls.rs
- libs/bebob/src/maudio/profirelightbridge_model.rs
- libs/bebob/src/maudio/special_ctls.rs
- libs/bebob/src/stanton.rs
- libs/core/src/card_cntr.rs
- libs/dg00x/Cargo.toml
- libs/dg00x/src/monitor_ctl.rs
- libs/efw/Cargo.toml
- libs/efw/src/mixer_ctl.rs
- libs/efw/src/output_ctl.rs
- libs/ta1394/src/audio.rs
In ALSA control interface, control element set can have data in TLV (Type-Length-Value) style. This data is added by kernel drivers or userspace applications, then it's referred by the other userspace applications.
This patchset adds a crate, alsa-ctl-tlv-codec to parse and build the data of TLV style. The crate is purely written by Rust and no dependency to the other crate or software, thus it's ready to publish.
This patchset also includes changes to existent crates for each vendor-dependent protocols and specification to use the crate for TLV data generation.
> alsa-ctl-tlv-codec: add crate to encode/decode TLV data in  ALSA control interface

- libs/bebob/Cargo.toml
- libs/core/Cargo.toml
- libs/core/src/card_cntr.rs
- libs/dg00x/Cargo.toml
- libs/efw/Cargo.toml
- libs/motu/Cargo.toml
- libs/oxfw/Cargo.toml
- libs/tascam/Cargo.toml
The new release of alsa-gobject is public and corresponding Rust crate
is also released.
This commit changes dependency version to the above so that new features
are available.
Signed-off-by: Takashi Sakamoto <o-takashi@sakamocchi.jp>
> update dependency version for alsa-gobject to v0.2.0 or later

- libs/core/src/elem_value_accessor.rs
Enough length of vactor is not allocated to store old and new element value.
This brings partial comparison between them and failure to handle write
request from applications.
This commit fixes the bug.
Fixes: 1ada77aa6414 ("core: add ElemValueAccessor trait and implement for each type of element value")
Signed-off-by: Takashi Sakamoto <o-takashi@sakamocchi.jp>
> core: elem_value_accessor: fix to read and compare element value

- libs/dice/protocols/src/maudio.rs
- libs/dice/runtime/src/pfire_model.rs
M-Audio ProFire 2626 supports two operations in application section 
of TCAT protocol extension. It has second optical interface and allows
software to decide which types of signal is used for the interface.
Additionally, it supports two types of mode for standalone converter.
Furthermore, it uses `Ins1` instead of `Ins0` for source and destination block.
This patchset improves support for M-Audio ProFire 2626
```
Takashi Sakamoto (5):
dice-protocols: maudio: add read method for master knob assignment
dice-runtime: pfire_model: use read transaction to get current assignment of master knob
dice-runtime: pfire_model: fix specification of ProFire 2626
dice-protocols: maudio: add methods specific to ProFire 2626
dice-runtime: pfire_model: add controls specific to ProFire 2626 …
```
> [PATCH 0/5] dice-runtime: improve support for M-Audio ProFire 2626

- libs/dice/runtime/src/mbox3_model.rs
ElemValueAccessor::get_vals() takes ElemValue structure for new values in
its first argument. However mbox3_model has call of the API with old values
in its first argument.
This commit fixes the bug.
Fixes: 9cf57f27073a ("dice-runtime: mbox3_model: add hardware control for Mbox 3 pro")
Signed-off-by: Takashi Sakamoto <o-takashi@sakamocchi.jp>
> dice-runtime: fix argument order to process value change correctly

- libs/alsa-ctl-tlv-codec/README.md
- libs/alsa-ctl-tlv-codec/src/containers.rs
- libs/alsa-ctl-tlv-codec/src/items.rs
- libs/alsa-ctl-tlv-codec/src/lib.rs
It's possible to add trait boundary to 'Vec::\<u32\>: From<&Self>' instead
of supertrait of 'Into::\<u32\>'.
Signed-off-by: Takashi Sakamoto <o-takashi@sakamocchi.jp>
> alsa-ctl-tlv-codec: use trait boundary to Vec::<u32>::from(&Self) Instead of Into::<u32>

- README.rst
- libs/dice/protocols/src/alesis.rs
- libs/dice/protocols/src/alesis/meter.rs
- libs/dice/protocols/src/alesis/mixer.rs
- libs/dice/protocols/src/alesis/output.rs
- libs/dice/protocols/src/lib.rs
- libs/dice/runtime/src/io_fw_model.rs
- libs/dice/runtime/src/lib.rs
- libs/dice/runtime/src/model.rs
Alesis shipped iO FireWire series 2006. Two models belongs to the series; iO 14 FireWire and iO 26 FireWire. Both of them utilizes DICE II ASIC as their communication engine and allows software to configure hardware features such like output volume.
This patchset adds support for the model. Additionally, this patchset adds entry to minimal model for MultiMix 8/12/16 FireWire shipped by Alesis 2005, as well as MasterControl shipped by Alesis 2009.
```
Takashi Sakamoto (11):
dice-runtime: add support for Alesis iO 14/26 FireWire
dice-runtime: alesis_model: detect iO 14 and iO 26
dice-protocols: add protocol specific to Alesis iO FireWire series
dice-protocols: alesis: add trait implementation for meter protocol
dice-runtime: alesis_model: add meter control for iO 14 and 26
dice-protocols: …
```
> [PATCH 00/10] dice: add support for Alesis iO FireWire series

- README.rst
- libs/dice/protocols/src/lexicon.rs
- libs/dice/protocols/src/lexicon/effect.rs
- libs/dice/protocols/src/lexicon/meter.rs
- libs/dice/protocols/src/lexicon/mixer.rs
- libs/dice/protocols/src/lib.rs
- libs/dice/runtime/src/ionix_model.rs
- libs/dice/runtime/src/lib.rs
- libs/dice/runtime/src/model.rs
I-ONIX FW810s was shipped in Lexicon brand of HARMAN International industries, Inc 2009. This model uses TCD2220 ASIC as its communication engine and support TCAT general protocol. Unique protocol is used to configure major functions such as audio signal routing, instead of TCAT protocol extension.
This patchset adds support for the model.
At this time, no controls are added for effect functions such as reverb. They can be controlled by write transaction to specific address with data frame which includes MIDI system exclusive message.  I investigated the message and realize that reverb effect requires multiple entities to be controlled. At present, ALSA control interface doesn't support such entities and I postpone its implementation
For yoru information, I write a sheet about the …
> dice: add support for Lexicon I-ONIX FW810s

- README.rst
- libs/dice/protocols/src/focusrite.rs
- libs/dice/protocols/src/focusrite/liquids56.rs
- libs/dice/protocols/src/focusrite/spro26.rs
- libs/dice/protocols/src/focusrite/spro40.rs
- libs/dice/protocols/src/lib.rs
- libs/dice/protocols/src/maudio.rs
- libs/dice/runtime/src/focusrite.rs
- libs/dice/runtime/src/focusrite/liquids56_model.rs
- libs/dice/runtime/src/focusrite/out_grp_ctl.rs
- libs/dice/runtime/src/focusrite/spro26_model.rs
- libs/dice/runtime/src/focusrite/spro40_model.rs
- libs/dice/runtime/src/lib.rs
- libs/dice/runtime/src/model.rs
- libs/dice/runtime/src/tcd22xx_ctl.rs
Focusrite Audio Engineering Ltd. produced Saffire Pro series between 2008 and 2014. The models in the series adopted TC Applied Technologies DICE TCD2220.
The models support TCAT protocol extension as well as unique protocol for output grouping. 
This patchset adds implementation of the protocol and support for the models.
```
dice-protocols: maudio: fix specification of M-Audio ProFire 2626
dice-runtime: focusrite: add support for Focusrite Saffire Pro 40
dice-runtime: focusrite: add support for Focusrite Liquid Saffire 56
dice-runtime: focusrite: add support for Focusrite Saffire Pro 26
dice-protocols: focusrite: add trait implementation for output group
protocol
dice-runtime: focusrinte: add output group controls
dice-protocols: focusrite: add trait …
```
> [PATCH 00/10]: dice: add support for Focusrite Saffire Pro series

- libs/dice/protocols/src/bin/tcat-extension-parser.rs
- libs/dice/protocols/src/tcat/extension.rs
- libs/dice/protocols/src/tcat/extension/current_config_section.rs
- libs/dice/protocols/src/tcat/extension/peak_section.rs
- libs/dice/protocols/src/tcat/extension/router_entry.rs
- libs/dice/protocols/src/tcat/extension/router_section.rs
- libs/dice/protocols/src/tcat/extension/stream_format_entry.rs
- libs/dice/protocols/src/tcat/extension/stream_format_section.rs
- libs/dice/protocols/src/tcat/tcd22xx_spec.rs
- libs/dice/runtime/src/tcd22xx_ctl.rs
Current implementation for TCAT protocol extension returns byte data to runtime crate, however it's inconvenient since the runtime requires recompile the data to structured data.
This patchset refactors the implementation to return the structured data instead of byte data.
```
Takashi Sakamoto (6):
dice-protocols: tcat: tcd22xx_spec: use structured data for router source and destination
dice-protocols: tcat: extension: return vector of RouterEntry instead of RouterEntryData
dice-protocols: tcat: extension: code refactoring to obsolete RouterEntryData
dice-protocols: tcat: extension: code refactoring to obsolete FormatEntryData
dice-protocols: tcat: tcd22xx_spec: optimization for fixed-position router entries
dice-protocols: tcat: extension: refine router entries with available sources and …
```
> [PATCH 0/6] dice-protocols: tcat: extension: code refactoring for router entries

- README.rst
- libs/dice/protocols/src/lib.rs
- libs/dice/protocols/src/presonus.rs
- libs/dice/protocols/src/presonus/fstudiomobile.rs
- libs/dice/protocols/src/presonus/fstudioproject.rs
- libs/dice/protocols/src/tcat/global_section.rs
- libs/dice/runtime/src/lib.rs
- libs/dice/runtime/src/model.rs
- libs/dice/runtime/src/presonus.rs
- libs/dice/runtime/src/presonus/fstudiomobile_model.rs
- libs/dice/runtime/src/presonus/fstudioproject_model.rs
FireStudio series was shipped by PreSonus Audio Electronics, Inc. 2007 to 2010. The models of series use TCAT DICE ASICs.
This commit adds support for a part of the series, which adapts to TCAT protocol extension.
```
Takashi Sakamoto (2):
dice-runtime: add support for PreSonus FireStudio Project
dice-runtime: add support for PreSonus FireStudio Mobile
libs/dice/protocols/src/lib.rs                |   1 +
libs/dice/protocols/src/presonus.rs           |   4 +
.../protocols/src/presonus/fstudiomobile.rs   |  34 +++++
.../protocols/src/presonus/fstudioproject.rs  |  40 ++++++
.../dice/protocols/src/tcat/global_section.rs |   2 +-
libs/dice/runtime/src/lib.rs                  |   1 +
libs/dice/runtime/src/model.rs                |  18 +++
libs/dice/runtime/src/presonus.rs             |   4 + …
```
> [PATCH 0/2] dice: add support for PreSonus FireStudio project/mobile

- README.rst
- libs/dice/protocols/src/presonus.rs
- libs/dice/protocols/src/presonus/fstudio.rs
- libs/dice/runtime/src/model.rs
- libs/dice/runtime/src/presonus.rs
- libs/dice/runtime/src/presonus/fstudio_model.rs
FireStudio was shipped by PreSonus Audio Electronics, Inc. 2007. The model uses TCAT Dice II ASIC and supports unique protocol to configure.
This patchset adds support for the model.
```
dice-runtime: add support for PreSonus FireStudio
dice-protocols: presonus: add trait implementation for protocol of FireStudio
dice-protocols: presonus: add trait implementation for meter protocol
dice-runtime: presonus: add meter controls for FireStudio
dice-protocols: presonus: add trait implementation for output protocol
dice-runtime: presonus: add output controls for FireStudio
dice-protocols: presonus: add trait implementation for assignment protocol
dice-runtime: presonus: add assignment controls for FireStudio
dice-protocols: presonus: add trait implementation for mixer …
```
> [PATCH 00/10] dice: add support for PreSonus FireStudio

- libs/dice/protocols/src/tcelectronic/studio.rs
- libs/dice/runtime/src/tcelectronic/studiok48_model.rs
TC Electronic Studio Konnekt 48 supports a function to aggregate several outputs to three groups for surround channels.
This commit supports the function.
```
Takashi Sakamoto (5):
dice-protocols: rename virtual speaker to output group
dice-protocols: tcelectronic: correct the number of entries for output mute and assignment to group
dice-runtime: tcelectronic: obsolete phys out level controls
dice-protocols: tcelectronic: add implementation for output group
dice-runtime: tcelectronic: add output group controls for Studio Konnekt 48
.../dice/protocols/src/tcelectronic/studio.rs | 203 +++++++++--
.../src/tcelectronic/studiok48_model.rs       | 331 +++++++++++++++---
2 files changed, 459 insertions(+), 75 deletions(-)
```
> [PATCH 0/5] dice-protocols: tcelectronic: add output group support for Studio Konnekt 48

- Cargo.toml
- README.rst
- libs/ff/protocols/src/former.rs
- libs/ff/protocols/src/former/ff400.rs
- libs/ff/protocols/src/former/ff800.rs
- libs/ff/protocols/src/latter.rs
- libs/ff/protocols/src/latter/ff802.rs
- libs/ff/protocols/src/latter/ucx.rs
- libs/ff/protocols/src/lib.rs
- libs/ff/runtime/Cargo.toml
- libs/ff/runtime/src/ff400_model.rs
- libs/ff/runtime/src/ff800_model.rs
- libs/ff/runtime/src/ff802_model.rs
- libs/ff/runtime/src/former_ctls.rs
- libs/ff/runtime/src/latter_ctls.rs
- libs/ff/runtime/src/lib.rs
- libs/ff/runtime/src/model.rs
- libs/ff/runtime/src/ucx_model.rs
- services/Cargo.toml
- services/src/bin/snd-fireface-ctl-service.rs
RME GmbH shipped some models in its Fireface series 2004 to 2014. The models are categorized to former and latter generation by protocol specification, programmed for FPGA. The latter models supports channel strip effect and reverb/echo fx effect.
This patchset adds support for the former and latter models. As a result, below models are controllable via ALSA control interface.
* Fireface 400
* Fireface 800
* Fireface UCX
* Fireface 802
```
Takashi Sakamoto (70):
ff-protocols: add crate for protocol implementation of RME Fireface series
ff-protocols: add trait implementation for parser of configuration rom by unique protocol
ff-protocols: add parser of configuration rom
ff-protocols: former: add module for protocol specific to former models of Fireface series
ff-protocols: former: add …
```
> [PATCH 00/70] ff: add service program for models in RME Fireface series

- libs/dice/runtime/src/tcd22xx_ctl.rs
- libs/efw/src/mixer_ctl.rs
- libs/efw/src/output_ctl.rs
In TLV-style data, dB value is in 0.01 unit.
> dice-runtime/efw: fix value for dB interval

- README.rst
- libs/bebob/src/apogee/apogee_model.rs
- libs/bebob/src/behringer/firepower_model.rs
- libs/bebob/src/esi.rs
- libs/bebob/src/lib.rs
- libs/bebob/src/maudio/audiophile_model.rs
- libs/bebob/src/maudio/fw410_model.rs
- libs/bebob/src/maudio/ozonic_model.rs
- libs/bebob/src/maudio/profirelightbridge_model.rs
- libs/bebob/src/maudio/solo_model.rs
- libs/bebob/src/maudio/special_model.rs
- libs/bebob/src/model.rs
- libs/bebob/src/stanton.rs
ESI Audiotechnik GmbH shipped Quatafire 610 2004. The model is based on
DM1000 in BridgeCo. Enhanced Breakout Box (BeBoB) as its communication
functionality.
This patchset adds support for the model.
```
Takashi Sakamoto (5):
bebob: use Default trait to instantiate each control model
bebob: implement Default trait for BebobAvc structure
bebob: add support fir ESI Quatafire 610
bebob: esi: add input controls for Quatafire
bebob: esi: add output control for Quatafire
libs/bebob/src/apogee/apogee_model.rs         |   8 +-
libs/bebob/src/behringer/firepower_model.rs   |   8 +-
libs/bebob/src/esi.rs                         | 278 ++++++++++++++++++
libs/bebob/src/lib.rs                         |   3 +-
libs/bebob/src/maudio/audiophile_model.rs     |  10 +-
libs/bebob/src/maudio/fw410_model.rs …
```
> [PATCH 0/5] bebob: ESI Quatafire 610 support

- libs/ieee1212-config-rom/src/lib.rs
When directory has single leaf/directory entry, the size of directory is 4
bytes (=1 quadlet). Current implementation expects the size greater than 8
and fail to parse in the case.
This commit fixes the bug.
> ieee1212-config-rom: fix size check for directory with single leaf/directory entry

- libs/ieee1212-config-rom/README.md
- libs/ieee1212-config-rom/src/bin/config-rom-parser.rs
- libs/ieee1212-config-rom/src/entry.rs
- libs/ieee1212-config-rom/src/leaf.rs
- libs/ieee1212-config-rom/src/lib.rs
In IEEE 1212, leaf is used for structured data and some types of structured data is defined. Current implementation of ieee1212-config-rom crate just supports descriptor type, however the other types are actually used in configuration ROM for Audio and Music units on IEEE 1394 bus.
This patchset adds support for some types.
```
Takashi Sakamoto (7):
ieee1212-config-rom: rename desc module to leaf module
ieee1212-config-rom: use generic structure for error to parse leaf
ieee1212-config-rom: rename Descriptor structure to DescriptorLeaf
ieee1212-config-rom: add Eui64 data structure and parser for leaf
ieee1212-config-rom: bin: parse EUI-64 leaf
ieee1212-config-rom: add unit location structure and parser for leaf
ieee1212-config-rom: bin: parse Unit Location leaf …
```
> [PATCH 0/7] ieee1212-config-rom: add parser for some types of data for leaf entry

- libs/bebob/src/runtime.rs
- libs/core/src/card_cntr.rs
- libs/core/src/dispatcher.rs
- libs/dg00x/src/runtime.rs
- libs/dice/runtime/src/lib.rs
- libs/efw/src/runtime.rs
- libs/ff/runtime/src/lib.rs
- libs/motu/src/runtime.rs
- libs/oxfw/runtime/src/lib.rs
- libs/tascam/src/async_runtime.rs
- libs/tascam/src/isoc_rack_runtime.rs
When implementation of RuntimeOperation::listen() fails due to ENOMEM
error in call of ioctl(2) with SNDRV_CTL_IOCTL_ELEM_ADD, the process
should be going to shutdown. However, preceding calls already queue
some ALSA control element event in kernel space. Running dispatcher
reads the events and sends to std::sync::mpsc, then possible to reach
the limit of queue in userspace. As a result, the sender thread is
blocked due to the lack of rest in the queue. In this case, the
shutdown corrupts due to thread joining even if glib::MainLoop is set
to quit.
Current implementation gives an internal API for the combination of
glib::MainLoop::quit() and std::Thread::join(). However, to release
the blocked thread, it's required to hollow the queue. This should
be done after scheduling stop of …
> core: dispatcher: fix thread blocking in shutdown process due to full queue

- README.rst
- libs/motu/protocols/src/lib.rs
- libs/motu/protocols/src/version_1.rs
- libs/motu/runtime/src/common_ctls.rs
- libs/motu/runtime/src/f828.rs
- libs/motu/runtime/src/f896.rs
- libs/motu/runtime/src/lib.rs
- libs/motu/runtime/src/model.rs
- libs/motu/runtime/src/v1_ctls.rs
ALSA firewire stack in Linux kernel v5.14 (probably) gains MOTU 828/896 support newly.
This patchset also adds support for the models with protocols to configure its functions
regardless of packet streaming.
```
Takashi Sakamoto (11):
motu-protocols: add trait for protocol of sample rate convert specific to AES/EBU signals
motu-protocols: add trait for protocol of level meters
motu-protocols: add implementation for protocol version 1
motu-runtime: add support for 828
motu-runtime: add support for 896
motu-runtime: add controls of sampling clock for version 1 models
motu-runtime: add control of monitor input for version 1 models
motu-runtime: add control of word out speed for 896
motu-runtime: add control of AES/EBU rate converter for 896
motu-runtime: add controls of level meters for 896 …
```
> [PATCH 00/11] motu-protocols/motu-runtime: add support for 828/896

- libs/efw/runtime/src/clk_ctl.rs
- libs/efw/runtime/src/guitar_ctl.rs
- libs/efw/runtime/src/iec60958_ctl.rs
- libs/efw/runtime/src/input_ctl.rs
- libs/efw/runtime/src/lib.rs
- libs/efw/runtime/src/meter_ctl.rs
- libs/efw/runtime/src/mixer_ctl.rs
- libs/efw/runtime/src/output_ctl.rs
- libs/efw/runtime/src/port_ctl.rs
The constant data during runtime can be assigned to static lifetime. In this patch, some arbitrary lifetime for the constant date is replaced with static lifetime.
> [PATCH] efw-runtime: use static lifetime for constant data during runtime

- README.rst
- libs/motu/protocols/src/lib.rs
- libs/motu/protocols/src/version_1.rs
- libs/motu/protocols/src/version_2.rs
- libs/motu/runtime/src/f896hd.rs
- libs/motu/runtime/src/lib.rs
- libs/motu/runtime/src/model.rs
Mark of the Unicorn (MOTU) shipped 896HD 2003 as one of models in second
generation of its FireWire series, and already discontinued it. The model
consists of below ICs:
* Texas Instruments TSB41AB2
* Phillips Semiconductors PDI1394L40
* Altera cyclone EP1C3
* Texas Instruments TMS320VC5402
It supports sampling transmission frequency up to 192.0 kHz. The packet
format differs depending on both of sampling transfer frequency and enabling
ADAT channels. The model doesn't support MIDI message transmission.
Like 896, the model supports below functions:
* Display meter
* AES/EBU sampling frequency converter
This patchset adds support for the model to operate the above functions.    
```
Takashi Sakamoto (2):
motu-protocols: add protocol implementation for 896HD
motu-runtime: add support for …
```
> [PATCH 0/2] motu-protocols/motu-runtime: add support for MOTU 896HD

- libs/bebob/protocols/src/focusrite.rs
- libs/bebob/protocols/src/focusrite/saffire.rs
- libs/bebob/runtime/src/focusrite.rs
- libs/bebob/runtime/src/focusrite/saffire_model.rs
Focusrite Saffire supports on-board audio effect and allows software to configure it. This
patchset adds support for the effect partly. The parameters of reverb and compressor are
clear but the ones of equalizer and amplifier are still unknown.
```
Takashi Sakamoto (8):
bebob-protocols: focusrite: saffire: read current value of monitor knob in meter protocol
bebob-protocols: focusrite: add argument to suppress parsing hwctl flag
bebob-protocols: focusrite: saffire: add protocol implementation to operate reverb effect parameters
bebob-runtime: focusrite: saffire_model: use protocol implementation of operation for reverb effect
bebob-protocols: focusrite: saffire: add protocol implementation to operate compressor effect
bebob-protocols: focusrite: saffire: add protocol implementation to …
```
> [PATCH 0/8] bebob-protocols: focusrite: saffire: add protocol implementation for audio effects

- libs/ff/protocols/src/former.rs
- libs/ff/protocols/src/former/ff400.rs
- libs/ff/protocols/src/former/ff800.rs
- libs/ff/protocols/src/latter.rs
- libs/ff/protocols/src/latter/ff802.rs
- libs/ff/protocols/src/latter/ucx.rs
- libs/ff/runtime/src/ff400_model.rs
- libs/ff/runtime/src/ff800_model.rs
- libs/ff/runtime/src/ff802_model.rs
- libs/ff/runtime/src/former_ctls.rs
- libs/ff/runtime/src/latter_ctls.rs
- libs/ff/runtime/src/ucx_model.rs
This patchset is to obsolete usage of AsRef trait for FwReq and FwNode.
```
Takashi Sakamoto (26):
ff-protocols: former: obsolete AsRef<FwNode> from trait of meter protocol
ff-protocols: former: obsolete AsRef<FwNode> from trait of output protocol
ff-protocols: former: obsolete AsRef<FwNode> from trait of mixer protocol
ff-protocols: former: ff400: integrate input amplifier protocol
ff-protocols: former: ff400: integrate status protocol
ff-protocols: former: ff400: integrate configuration protocol
ff-protocols: former: ff800: integrate status protocol
ff-protocols: former: ff800: integrate configuration protocol
ff-protocols: latter: obsolete AsRef<FwNode> from trait of configuration protocol
ff-protocols: latter: obsolete AsRef<FwNode> from trait of status protocol
ff-protocols: latter: …
```
> [PATCH 00/26] ff-protocols/ff-runtime: code refactoring to obsolete AsRef for FwReq and FwNode

- libs/dg00x/runtime/src/model.rs
- libs/efw/runtime/src/clk_ctl.rs
- libs/efw/runtime/src/guitar_ctl.rs
- libs/efw/runtime/src/iec60958_ctl.rs
- libs/efw/runtime/src/input_ctl.rs
- libs/efw/runtime/src/meter_ctl.rs
- libs/efw/runtime/src/mixer_ctl.rs
- libs/efw/runtime/src/model.rs
- libs/efw/runtime/src/output_ctl.rs
- libs/efw/runtime/src/port_ctl.rs
- libs/tascam/runtime/src/asynch_runtime.rs
- libs/tascam/runtime/src/fe8_model.rs
- libs/tascam/runtime/src/fw1082_model.rs
- libs/tascam/runtime/src/fw1804_model.rs
- libs/tascam/runtime/src/fw1884_model.rs
- libs/tascam/runtime/src/isoch_console_runtime.rs
- libs/tascam/runtime/src/isoch_ctls.rs
- libs/tascam/runtime/src/isoch_rack_runtime.rs
- libs/tascam/runtime/src/lib.rs
This patchset is to refactor runtime crate of dg00x, efw, and tascam. Especially, generic structure is heavily used
to abstract runtime structure.
```
Takashi Sakamoto (13):
tascam-runtime: isoch_ctls: obsolete AsRef/AsMut implementation in meter control
tascam-runtime: isoch_ctls: rename trait of common control for naming consistency
tascam-runtime: isoch_ctls: rename trait of optical interface control for naming consistency
tascam-runtime: isoch_ctls: obsolete AsRef/AsMut implementation in console control
tascam-runtime: isoch_ctls: obsolete AsRef/AsMut implementation in rack control
tascam-runtime: isoch_ctls: obsolete AsRef/AsMut implementation in surface event dispatcher
tascam-runtime: minor code refactoring for isoch console runtime
tascam-runtime: use generic structure for runtime …
```
> [PATCH 00/13] dg00x/efw/tascam: code refactoring for runtime crate

- README.rst
- libs/dice/protocols/src/focusrite.rs
- libs/dice/protocols/src/focusrite/liquids56.rs
- libs/dice/protocols/src/focusrite/spro14.rs
- libs/dice/protocols/src/focusrite/spro24.rs
- libs/dice/protocols/src/focusrite/spro24dsp.rs
- libs/dice/protocols/src/focusrite/spro26.rs
- libs/dice/protocols/src/focusrite/spro40.rs
- libs/dice/runtime/src/focusrite.rs
- libs/dice/runtime/src/focusrite/spro14_model.rs
- libs/dice/runtime/src/focusrite/spro24_model.rs
- libs/dice/runtime/src/focusrite/spro24dsp_model.rs
- libs/dice/runtime/src/model.rs
Hi,
This patchset adds support for below models based on TCD2220:
* Focusrite Saffire Pro 14
* Focusrite Saffire Pro 24
* Focusrite Saffire Pro 24 DSP
Especially, for Pro 24 DSP, channel strip and reverb effects are partially supported.
```
Takashi Sakamoto (21):
dice-protocols: focusrite: add trait and implementation for software notice protocol
dice-protocols: focusrite: add protocol implementation for Focusrite Saffire Pro 14
dice-protocols: focusrite: add implementaion of output group protocol for Pro 14
dice-protocols: focusrite: add trait and implementation for input protocol for Pro 14 and 24
dice-protocols: focusrite: add protocol implementation for Focusrite Saffire Pro 24
dice-protocols: focusrite: add implementaion of output group protocol for Pro 24
dice-protocols: focusrite: …
```
> [PATCH 00/21] dice-protocols/dice-runtime: add support for Focusrite Saffire Pro 14, 24, and 24 DSP

- README.rst
- libs/efw/protocols/src/hw_info.rs
- libs/efw/protocols/src/lib.rs
- libs/efw/protocols/src/port_conf.rs
- libs/efw/runtime/src/clk_ctl.rs
- libs/efw/runtime/src/guitar_ctl.rs
- libs/efw/runtime/src/iec60958_ctl.rs
- libs/efw/runtime/src/input_ctl.rs
- libs/efw/runtime/src/lib.rs
- libs/efw/runtime/src/meter_ctl.rs
- libs/efw/runtime/src/mixer_ctl.rs
- libs/efw/runtime/src/model.rs
- libs/efw/runtime/src/output_ctl.rs
- libs/efw/runtime/src/port_ctl.rs
Current implementation of Fireworks protocol includes wrong interpretation for digital interface capabilities.
Additionally, stream map protocol requires sampling transfer frequency as its first argument.
Furthermore, reported at #50, Onyx 1200f/400f reject playback solo command.
This commit fixes the above items.
```
Takashi Sakamoto (17):
efw-runtime: opt out Onyx 1200F from nominal input controls
efw-protocols: fixup hardware information for Onyx 1200f
efw-runtime: code refactoring to declare usage of modules
efw-runtime: code refactoring for name of list for measured elements
efw-runtime: add trait implementationn for stream lock notification
efw-runtime: handle stream lock notification to update cache for clock controls
efw-runtime: cache current state of stream map
efw-runtime: …
```
> [PATCH 00/17] efw-protocols/efw-runtime: fix bug for protocol implementation

- README.rst
- libs/ieee1212-config-rom/Cargo.toml
- libs/ieee1212-config-rom/README.md
- libs/ieee1212-config-rom/src/entry.rs
- libs/ieee1212-config-rom/src/leaf.rs
- libs/ieee1212-config-rom/src/lib.rs
This patchset is code refactoring for publishing ieee1212-config-rom crate.
Due to convention of Rust ecosystem, license is changed to MIT.
```
ieee1212-config-rom: code refactoring to handle Result enumeration
ieee1212-config-rom: change license to MIT
ieee1212-config-rom: improve documentation
ieee1212-config-rom: fulfill package section for publishing
README.rst                            |   2 +-
libs/ieee1212-config-rom/Cargo.toml   |   7 +-
libs/ieee1212-config-rom/README.md    |  19 +++-
libs/ieee1212-config-rom/src/entry.rs |  10 +-
libs/ieee1212-config-rom/src/leaf.rs  | 115 ++++++++-----------
libs/ieee1212-config-rom/src/lib.rs   | 155 ++++++++++++++------------
6 files changed, 155 insertions(+), 153 deletions(-)
```
> ieee1212-config-rom: code refactoring for publishing

- README.rst
- libs/alsa-ctl-tlv-codec/README.md
- libs/ieee1212-config-rom/src/leaf.rs
- libs/ieee1212-config-rom/src/lib.rs
Current implementation supports error reporting for failure to parse the content of
Configuration ROM, however it is not enough modern and friendly.
This patchset improves it as well as any bug-fixes.
```
alsa-ctl-tlv-codec: fix copy-and-paste mistake
ieee1212-config-rom: fix invalid operation for value of CSR Offset Leaf
ieee1212-config-rom: replace hardcoded numeric value with named constants.
ieee1212-config-rom: assert when the key of entry is beyond 0x3
ieee1212-config-rom: code refactoring to keep parse cursor
ieee1212-config-rom: add helper function to parse directory content
ieee1212-config-rom: enhancement for error reporting of config rom parser
ieee1212-config-rom: add helper function to detect leaf from entry
ieee1212-config-rom: enhancement for error …
```
> [PATCH 0/10] ieee1212-config-rom: enhancement for error reporting

- Cargo.toml
- libs/ta1394/ccm/src/lib.rs
- libs/ta1394/general/src/general.rs
- libs/ta1394/general/src/lib.rs
Current implementation of general and ccm crates have lack of implementation of
Defailt trait for some public structures. It`s not necessarily convenient. Additionally,
it`s not convenient to implement serializer/deserializer by From trait for local usage.
This patchset refactors the crates.
```
Takashi Sakamoto (12):
ta1394/general: start crate development for v0.2.0
ta1394/general: implement Default trait for AvcAddr
ta1394/general: implement Default trait for AvcCmdType
ta1394/general: implement Default trait for AvcRespCode
ta1394/general: implement Default trait for UnitInfo
ta1394/general: implement Default trait for SubunitInfo
ta1394/general: implement Default trait for VendorDependent
ta1394/general: implement Default trait for PlugInfo
ta1394/ccm: start crate development for …
```
> [PATCH 00/12] ta1394: code refactoring for general and ccm crates

- Cargo.toml
- libs/bebob/protocols/src/bridgeco.rs
- libs/ta1394/stream-format/src/lib.rs
This patchset includes code refactoring for stream format commands.
```
Takashi Sakamoto (11):
bebob/protocols: start crate development for v0.2.0
bebob/protocols: implement unique support status
ta1394/stream-format: start crate development for v0.2.0
ta1394/stream-format: localize serializer/deserializer for StreamFormat
ta1394/stream-format: localize serializer/deserializer for PlugAddr
ta1394/stream-format: localize serializer/deserializer for SupportStatus
ta1394/stream-format: implement Default trait for StreamFormat
ta1394/stream-format: implement Default trait for PlugAddr
ta1394/stream-format: implement Default trait for SupportStatus
ta1394/stream-format: implement Default trait for ExtendedStreamFormat
ta1394/stream-format: code refactoring for ExtendedStreamFormatSingle
and …
```
> [PATCH 00/11] ta1394/stream-format: code refactoring for stream format commands

- Cargo.toml
- libs/dice/protocols/src/focusrite/spro40.rs
Hi. Sorry it was easier to just make a new PR, fix is same as before. Hope it's closer to what you were asking there. All details are as in pr #104 
replaces:
* pr #104
fixes:
* issue #92
* Fixes: missing last 2 analog input channels `6+7` (from index starting `0`)
* Solution: fill complete `ins1` inputs from `6` --> `8` (i2c in direction, into the DICE chip)
closes:
* pr #104
* issue #92
> dice/audio: fix audio channels - spro40

- Cargo.toml
- libs/bebob/protocols/src/icon.rs
- libs/bebob/protocols/src/lib.rs
- libs/bebob/protocols/src/presonus/firebox.rs
- libs/bebob/protocols/src/presonus/inspire1394.rs
- libs/bebob/protocols/src/terratec/aureon.rs
- libs/bebob/protocols/src/yamaha_terratec.rs
- libs/oxfw/protocols/src/griffin.rs
- libs/oxfw/protocols/src/lacie.rs
- libs/ta1394/audio/src/lib.rs
Current implementation includes wrong interpretation for audio channel in AV/C audio
subunit commands. This patchset includes fix as well as rewriting data of feature function block
command.
```
Takashi Sakamoto (19):
ta1394/audio: start crate development for v0.2.0
oxfw/protocols: start crate development for v0.2.0
ta1394/audio: fix value for audio channel
ta1394/audio: localize serializer/deserializer for AudioFuncBlkType
ta1394/audio: localize serializer/deserializer for CtlAttr structure
ta1394/audio: code refactoring for AudioFuncBlkCtl
ta1394/audio: code refactoring for AudioFuncBlk
ta1394/audio: localize serializer/deserializer for FeatureCtl
ta1394/audio: localize serializer/deserializer for ProcessingCtl
ta1394/audio: implement Default trait for Audio Function Block command …
```
> [PATCH 00/19] ta1394/audio: fix audio channel and rewrite feature data

- libs/bebob/protocols/src/apogee/ensemble.rs
- libs/bebob/protocols/src/bridgeco.rs
- libs/bebob/protocols/src/lib.rs
- libs/bebob/protocols/src/maudio/normal.rs
This patchset includes many code changes mainly to reduce unnecessary trait implementations and internal panics.
```
Takashi Sakamoto (27):
bebob/protocols: localize serializer/deserializer for BcoPlugAddr
bebob/protocols: localize serializer/deserializer for BcoIoPlugAddr
bebob/protocols: localize serializer/deserializer for BcoPlugType
bebob/protocols: localize serializer/deserializer for BcoCluster
bebob/protocols: localize serializer/deserializer for BcoClusterInfo
bebob/protocols: localize serializer/deserializer for BcoPortType
bebob/protocols: localize serializer/deserializer for BcoPlugInfo
bebob/protocols: localize serializer/deserializer for ExtendedSubunitInfoEntry
bebob/protocols: localize serializer/deserializer for BcoCompoundAm824Stream
bebob/protocols: localize …
```
> [PATCH 00/27] bebob/protocols: code cleanup

- README.rst
- runtime/bebob/Cargo.toml
- runtime/bebob/src/bin/snd-bebob-ctl-service.rs
- runtime/bebob/src/lib.rs
- runtime/core/Cargo.toml
- runtime/core/src/cmdline.rs
- runtime/dice/Cargo.toml
- runtime/dice/src/bin/snd-dice-ctl-service.rs
- runtime/digi00x/Cargo.toml
- runtime/digi00x/src/bin/snd-firewire-digi00x-ctl-service.rs
- runtime/digi00x/src/lib.rs
- runtime/fireface/Cargo.toml
- runtime/fireface/src/bin/snd-fireface-ctl-service.rs
- runtime/fireface/src/lib.rs
- runtime/fireworks/Cargo.toml
- runtime/fireworks/src/bin/snd-fireworks-ctl-service.rs
- runtime/motu/Cargo.toml
- runtime/motu/src/bin/snd-firewire-motu-ctl-service.rs
- runtime/oxfw/Cargo.toml
- runtime/oxfw/src/bin/snd-oxfw-ctl-service.rs
- runtime/oxfw/src/common_model.rs
- runtime/oxfw/src/lib.rs
- runtime/tascam/Cargo.toml
- runtime/tascam/src/bin/snd-firewire-tascam-ctl-service.rs
Current implementation includes code to parse arguments of command line,
while we have useful crate for the purpose; [clap crate](https://crates.io/crates/clap).
This commit adds new dependency to clap crate to obsolete own implementation
to parse the arguments. It brings a space to extend command line with additional
arguments, therefore it may be preferable.
```
runtime/oxfw: remove useless named lifetime for CommonModel
runtime/all: use static lifetime instead of named lifetime at top-level structure
runtime/all: parse command line argument by clap crate
runtime/core: use clap crate to build command
README.rst                                    |   7 +-
runtime/bebob/Cargo.toml                      |   1 +
.../bebob/src/bin/snd-bebob-ctl-service.rs    |  17 +- …
```
> [PATCH 0/4] runtime: use clap crate to parse arguments of command line

- runtime/motu/src/audioexpress.rs
- runtime/motu/src/command_dsp_ctls.rs
- runtime/motu/src/f828mk2.rs
- runtime/motu/src/f828mk3.rs
- runtime/motu/src/f828mk3_hybrid.rs
- runtime/motu/src/f896hd.rs
- runtime/motu/src/f8pre.rs
- runtime/motu/src/h4pre.rs
- runtime/motu/src/register_dsp_ctls.rs
- runtime/motu/src/track16.rs
- runtime/motu/src/traveler.rs
- runtime/motu/src/traveler_mk3.rs
- runtime/motu/src/ultralite.rs
- runtime/motu/src/ultralite_mk3.rs
- runtime/motu/src/ultralite_mk3_hybrid.rs
Current implementation instantiates parameters inner helper trait,
while it's preferable to implement Default trait for the purpose.
This patchset adds Default trait implementations for each models for the purpose.
```
runtime/motu: code refactoring for mixer parameters of command DSP models
runtime/motu: code refactoring for input parameters of command DSP models
runtime/motu: code refactoring for output parameters of command DSP models
runtime/motu: code refactoring for meter state of command DSP models
runtime/motu: code refactoring for meter state of register DSP models
runtime/motu: code refactoring for monaural mixer source of register DSP models
runtime/motu: code refactoring for stereo mixer source of register DSP models
runtime/motu: code refactoring for …
```
> [PATCH 00/10] runtime/motu: code refactoring to use Debug trait implementation

- protocols/bebob/src/apogee/ensemble.rs
- runtime/bebob/src/apogee/ensemble_model.rs
The parameters of Ensemble model have no tests. It's not preferable.
This patchset reorganize implementation of parameters and protocols by adding
converter between parameters and vendor-dependent AV/C command operation
with enough tests.
```
Takashi Sakamoto (6):
protocols/bebob: apogee: implement converter to parameters for vendor specific command
protocols/bebob: apogee: rename public methods to update hardware for parameters
runtime/bebob: apogee: code refactoring for cache function
runtime/bebob: apogee: implement Debug trait for specific controls
protocols/bebob: apogee: add doc comments to parameters
protocols/bebob: apogee: add doc comments to vendor specific commands
protocols/bebob/src/apogee/ensemble.rs     | 808 ++++++++++++++++++---
runtime/bebob/src/apogee/ensemble_model.rs …
```
> [PATCH 0/6] runtime/bebob: apogee: add conveter between parameters and commands

- README.rst
- runtime/dice/Cargo.toml
- runtime/dice/src/bin/snd-dice-ctl-service.rs
- runtime/dice/src/common_ctl.rs
- runtime/dice/src/lib.rs
It's really helpful to dump logs for debugging purpose. This patchset utilizes
tracing and tracing-subscriber crates for the purpose. An option is newly added
to dice runtime, then implement tracing events.
At present, common controls and corresponding protocol parameters are target
of logging. The other parameters will be added in future commits.
```
Takashi Sakamoto (3):
runtime/dice: use tracing-subscriber crate to dump debug logs
runtime/dice: add tracing span and event to runtime structure
runtime/dice: add tracing event to common controls
README.rst                                   |  18 ++-
runtime/dice/Cargo.toml                      |   2 +
runtime/dice/src/bin/snd-dice-ctl-service.rs |   6 +-
runtime/dice/src/common_ctl.rs               |  45 ++++++--
runtime/dice/src/lib.rs …
```
> [PATCH 0/3] runtime/dice: support debug logging by tracing crate

- protocols/dice/src/tcat.rs
- protocols/dice/src/tcelectronic.rs
- protocols/dice/src/tcelectronic/ch_strip.rs
- protocols/dice/src/tcelectronic/desktop.rs
- protocols/dice/src/tcelectronic/fw_led.rs
- protocols/dice/src/tcelectronic/midi_send.rs
- protocols/dice/src/tcelectronic/prog.rs
- protocols/dice/src/tcelectronic/reverb.rs
- protocols/dice/src/tcelectronic/shell.rs
- protocols/dice/src/tcelectronic/shell/itwin.rs
- protocols/dice/src/tcelectronic/shell/k24d.rs
- protocols/dice/src/tcelectronic/shell/k8.rs
- protocols/dice/src/tcelectronic/shell/klive.rs
- protocols/dice/src/tcelectronic/standalone.rs
- protocols/dice/src/tcelectronic/studio.rs
- runtime/dice/src/tcelectronic/ch_strip_ctl.rs
- runtime/dice/src/tcelectronic/desktopk6_model.rs
- runtime/dice/src/tcelectronic/fw_led_ctl.rs
- runtime/dice/src/tcelectronic/itwin_model.rs
- runtime/dice/src/tcelectronic/k24d_model.rs
- runtime/dice/src/tcelectronic/k8_model.rs
- runtime/dice/src/tcelectronic/klive_model.rs
- runtime/dice/src/tcelectronic/midi_send_ctl.rs
- runtime/dice/src/tcelectronic/prog_ctl.rs
- runtime/dice/src/tcelectronic/reverb_ctl.rs
- runtime/dice/src/tcelectronic/shell_ctl.rs
- runtime/dice/src/tcelectronic/standalone_ctl.rs
- runtime/dice/src/tcelectronic/studiok48_model.rs
Current implementation for protocol specific to TC Electronic has issue that
intermediate data expression has parameters to operate protocol. It's preferable
to move these parameters to protocol implementations.
This patchset is for the purpose.
```
Takashi Sakamoto (23):
protocols/dice: tcat: expand error domain for vendor dependent protocols
protocols/dice: tcelectronic: tcelectronic: add trait to revise current implementation
protocols/dice: tcelectronic: use renewed trait for Desktop Konnekt 6
protocols/dice: tcelectronic: implement renewed trait for Studio Konnekt 48
protocols/dice: tcelectronic: implement renewed trait for Konnekt 8
protocols/dice: tcelectronic: implement renewed trait for Konnekt 24
protocols/dice: tcelectronic: implement renewed trait for Konnekt Live …
```
> [PATCH 00/23] protocols/dice: tcelectronic: renew protocol traits

- protocols/dice/src/presonus/fstudio.rs
- protocols/dice/src/tcelectronic.rs
- runtime/dice/src/presonus/fstudio_model.rs
This batch of patch is to rework for protocol implementation of PreSonus FireStudio
as well as adding logging to control runtime.
```
protocols/dice: presonus: add renewed trait for hardware parameters
protocols/dice: presonus: implement serializer/deserializer for meter parameters
protocols/dice: presonus: implement serializer/deserializer for output parameters
protocols/dice: presonus: implement serializer/deserializer for mixer parameters
protocols/dice: presonus: update doc comment for protocol of FireStudio
runtime/dice: presonus: use renewed trait implementation for meter controls
runtime/dice: presonus: use renewed trait implementation for output controls
runtime/dice: presonus: use renewed trait implementation for mixer parameters of FireStudio …
```
> [PATCH 00/10] protocols/dice: presonus: rework for protocol implementation of FireStudio

- protocols/dice/src/lexicon.rs
- runtime/dice/src/ionix_model.rs
This patchset is rework for protocol implementation of i-onix fw810s.
Some renewed traits are newly added to obsolete old implementations.
```
Takashi Sakamoto (9):
protocols/dice: lexicon: add renewed trait for protocol of i-onix fw810s
protocols/dice: lexicon: add renewed trait implementation for meter operation
protocols/dice: lexicon: add renewed trait implementation for mixer operation
protocols/dice: lexicon: add renewed trait implementation for effect operation
protocols/dice: lexicon: fulfill doc comment for better documentation
runtime/dice: lexicon: use renewed trait implementation for meter parameters
runtime/dice: lexicon: use renewed trait implementation for mixer parameters
runtime/dice: lexicon: add logging for specific controls
protocols/dice: lexicon: remove unused traits …
```
> [PATCH 0/9] protocols/dice: lexicon: rework for protocol implementation of i-onix fw810s

- protocols/dice/src/avid.rs
- runtime/dice/src/mbox3_model.rs
This patchset is rework for protocol implementation of Mbox 3 pro so that
intermediate structure of parameters is used between protocol and runtime
implementations.
```
protocols/dice: avid: add intermediate structure of parameters for runtime
runtime/dice: avid: use intermediate structure of parameters
protocols/dice: avid: remove unused methods from trait of protocol
runtime/dice: avid: add logging to controls specific to Profire series
protocols/dice/src/avid.rs      | 1143 ++++++++++++++----------------
runtime/dice/src/mbox3_model.rs | 1180 ++++++++++++++-----------------
2 files changed, 1075 insertions(+), 1248 deletions(-)
```
> [PATCH 0/4] protocols/dice: avid: rework for protocol implementation of Mbox 3 pro

- protocols/dice/src/maudio.rs
- runtime/dice/src/pfire_model.rs
This patchset is rework for protocol implementation of Profire series so that
intermediate structure of parameters is used between protocol and runtime
implementations.
```
protocols/dice: maudio: add intermediate structure of parameters for runtime
runtime/dice: maudio: use intermediate structure of parameters
protocols/dice: maudio: remove unused methods from trait of protocol
runtime/dice: maudio: add logging to controls specific to Profire series
protocols/dice/src/maudio.rs    | 303 +++++++++++++++-----------------
runtime/dice/src/pfire_model.rs | 165 ++++++++---------
2 files changed, 214 insertions(+), 254 deletions(-)
```
> [PATCH 0/4] protocols/dice: maudio: rework for protocol implementation of Profire series

- protocols/dice/src/bin/tcat-extension-parser.rs
- protocols/dice/src/tcat/extension/standalone_section.rs
- runtime/dice/src/blackbird_model.rs
- runtime/dice/src/common_ctl.rs
- runtime/dice/src/extension_model.rs
- runtime/dice/src/focusrite/liquids56_model.rs
- runtime/dice/src/focusrite/spro14_model.rs
- runtime/dice/src/focusrite/spro24_model.rs
- runtime/dice/src/focusrite/spro24dsp_model.rs
- runtime/dice/src/focusrite/spro26_model.rs
- runtime/dice/src/focusrite/spro40_model.rs
- runtime/dice/src/io_fw_model.rs
- runtime/dice/src/ionix_model.rs
- runtime/dice/src/lib.rs
- runtime/dice/src/mbox3_model.rs
- runtime/dice/src/minimal_model.rs
- runtime/dice/src/pfire_model.rs
- runtime/dice/src/presonus/fstudio_model.rs
- runtime/dice/src/presonus/fstudiomobile_model.rs
- runtime/dice/src/presonus/fstudioproject_model.rs
- runtime/dice/src/tcd22xx_ctl.rs
- runtime/dice/src/tcelectronic/desktopk6_model.rs
- runtime/dice/src/tcelectronic/itwin_model.rs
- runtime/dice/src/tcelectronic/k24d_model.rs
- runtime/dice/src/tcelectronic/k8_model.rs
- runtime/dice/src/tcelectronic/klive_model.rs
- runtime/dice/src/tcelectronic/studiok48_model.rs
Current implementation of controls related to TCD22xx includes duplicated hardware data.
This patchset cleans up the redundancy as well as adding intermediate structure expression
for some parameters.
```
Takashi Sakamoto (14):
runtime/dice: common_ctl: use generic structure for common controls
runtime/dice: tcd22xx_ctl: code refactoring to receive global parameters
runtime/dice: tcd22xx_ctl: code refactoring for ADAT and Word Clock modes
protocols/dice: tcat: add intermediate structure expression for standalone configuration parameters
runtime/dice: tcd22xx_ctls: use cached parameter for standalone configuration
protocols/dice: tcat: remove unused functions for extension protocol
runtime/dice: tcd22xx_ctl: code refactoring to split cache function
runtime/dice: tcd22xx_ctl: unify element …
```
> [PATCH 00/14] runtime/dice: rework for controls of TCD22xx

- protocols/dice/src/tcat/tcd22xx_spec.rs
- runtime/dice/src/blackbird_model.rs
- runtime/dice/src/extension_model.rs
- runtime/dice/src/focusrite/liquids56_model.rs
- runtime/dice/src/focusrite/spro14_model.rs
- runtime/dice/src/focusrite/spro24_model.rs
- runtime/dice/src/focusrite/spro24dsp_model.rs
- runtime/dice/src/focusrite/spro26_model.rs
- runtime/dice/src/focusrite/spro40_model.rs
- runtime/dice/src/lib.rs
- runtime/dice/src/mbox3_model.rs
- runtime/dice/src/model.rs
- runtime/dice/src/pfire_model.rs
- runtime/dice/src/presonus/fstudiomobile_model.rs
- runtime/dice/src/presonus/fstudioproject_model.rs
- runtime/dice/src/tcd22xx_ctl.rs
Current implementation of TCD22xx operation includes some inconvenience.
This patchset is to arrange the implementation.
```
Takashi Sakamoto (7):
protocols/dice: tcat: arrangement to detect available source and destination blocks of TCD22xx
protocols/dice: tcat: arrangement for argument order
protocols/dice: tcat: move string generator for source and destination blocks of TCD22xx
runtime/dice: tcd22xx_ctl: start channel index at 1 instead of 0
runtime/dice: tcd22xx_ctl: use stream label "Stream" if single stream is just supported
protocols/dice: tcat: fulfill doc comment for operation specific to TCD22xx
runtime/dice: tcd22xx_ctl: store configuration to on-board flash memory when terminated
protocols/dice/src/tcat/tcd22xx_spec.rs       | 137 ++++++------------ …
```
> [PATCH 0/7] protocols/dice: tcat: some arrangements for TCD22xx implementation

- protocols/dice/src/focusrite.rs
- runtime/dice/src/focusrite.rs
This patchset is to fix issue reported at #91. The value of volume in output group
parameter should be inverted correctly.
```
protocols/dice: focusrite: hard code minimum and maximum value of volume in output group
protocols/dice: focusrite: invert value of volume in output group
runtime/dice: focusrite: obsolete inversion calculation for output group control
runtime/dice: focusrite: rename controls for output group
protocols/dice/src/focusrite.rs | 32 ++++++++++++++++++++++++-----
runtime/dice/src/focusrite.rs   | 36 +++++++++++++++------------------
2 files changed, 43 insertions(+), 25 deletions(-)
```
> [PATCH 0/4] protocols/dice: focusrite: fix volume operation in output group parameter

- README.rst
- protocols/dice/README.md
- protocols/dice/src/presonus.rs
- protocols/dice/src/presonus/fstudiotube.rs
- runtime/dice/src/focusrite.rs
- runtime/dice/src/model.rs
- runtime/dice/src/presonus.rs
- runtime/dice/src/presonus/fstudiotube_model.rs
This patchset adds support for Presonus FireStudio Tube. It uses TCAT TCD2210 ASIC and support TCAT protocol extension.
```
Takashi Sakamoto (2):
protocols/dice: add protocol implementation for FireStudio Tube
runtime/dice: add support for FireStudio Tube
README.rst                                    |   1 +
protocols/dice/README.md                      |   1 +
protocols/dice/src/presonus.rs                |   1 +
protocols/dice/src/presonus/fstudiotube.rs    |  34 ++++
runtime/dice/src/model.rs                     |  22 +-
runtime/dice/src/presonus.rs                  |   1 +
.../dice/src/presonus/fstudiotube_model.rs    | 189 ++++++++++++++++++
7 files changed, 246 insertions(+), 3 deletions(-)
create mode 100644 protocols/dice/src/presonus/fstudiotube.rs
create mode 100644 …
```
> [PATCH 0/2] dice: add support for Presonus FireStudio Tube

- Cargo.toml
- protocols/fireface/src/latter.rs
- runtime/fireface/src/latter_ctls.rs
This patchset fixes protocol implementation for microphone phantom powering and instrument. The issue was reported at #44 . Additionally, fix mic bugs as well.
```
fireface/protocols: start crate development for v0.2.0
protocols/fireface: fix invalid index of microphone inputs
runtime/fireface: fix out-of-bounds access
runtime/fireface: fix invalid channel count for output parameters in
latter models
Cargo.toml                          |  4 +--
protocols/fireface/src/latter.rs    | 44 ++++++++++++-----------
runtime/fireface/src/latter_ctls.rs | 54 +++++++++++++++++------------
3 files changed, 56 insertions(+), 46 deletions(-)
```
> [PATCH 0/4] protocols/fireface: fix for microphone phantom powering and instrument

- README.rst
- protocols/fireface/src/bin/ff-config-rom-parser.rs
- protocols/fireface/src/former.rs
- protocols/fireface/src/former/ff400.rs
- protocols/fireface/src/former/ff800.rs
- protocols/fireface/src/latter.rs
- protocols/fireface/src/latter/ff802.rs
- protocols/fireface/src/latter/ucx.rs
- runtime/fireface/Cargo.toml
- runtime/fireface/src/bin/snd-fireface-ctl-service.rs
- runtime/fireface/src/ff400_model.rs
- runtime/fireface/src/ff800_model.rs
- runtime/fireface/src/ff802_model.rs
- runtime/fireface/src/former_ctls.rs
- runtime/fireface/src/latter_ctls.rs
- runtime/fireface/src/lib.rs
- runtime/fireface/src/model.rs
- runtime/fireface/src/ucx_model.rs
It's really helpful to dump logs for debugging purpose. This patchset utilizes
tracing and tracing-subscriber crates for the purpose. An option is newly added
to fireface runtime, then implement tracing events.
```
Takashi Sakamoto (18):
protocols/fireface: arrangement of derive traits for protocol
implementations
runtime/fireface: use generic structure for meter controls in former
models
runtime/fireface: use generic structure for output control in former
models
runtime/fireface: use generic structure for mixer controls in former
models
runtime/fireface: code refactoring for controls specific to Fireface
400
runtime/fireface: code refactoring for controls specific to Fireface
800
runtime/fireface: use generic structure for meter controls in latter
models
runtime/fireface: use generic …
```
> [PATCH 00/18] runtime/fireface: support debug logging by tracing crate

- protocols/fireface/src/former.rs
- protocols/fireface/src/former/ff400.rs
- protocols/fireface/src/former/ff800.rs
- protocols/fireface/src/latter.rs
- protocols/fireface/src/latter/ff802.rs
- protocols/fireface/src/latter/ucx.rs
- protocols/fireface/src/lib.rs
- runtime/fireface/src/ff400_model.rs
- runtime/fireface/src/ff800_model.rs
- runtime/fireface/src/ff802_model.rs
- runtime/fireface/src/ucx_model.rs
The typical way to operate devices of RME FireFace series is accessing
to registers by read and write transaction. The operation could consists of
deserializer/serializer and read/write transaction.
This patchset arranges current implementations to add some traits for the
purpose and to use their implementations. As a result, the previous implementations
are obsoleted.
```
Takashi Sakamoto (19):
protocols/fireface: add trait to serialize/deserialize parameters
protocols/fireface: implement trait to serialize/deserialize
configuration in Fireface 800
protocols/fireface: implement trait to serialize/deserialize
configuration in Fireface 400
protocols/fireface: add trait to update whole parameters at once
protocols/fireface: implement trait to update configuration in former
models …
```
> [PATCH 00/19] protocols/fireface: add common trait to operate configuration and status registers

- protocols/fireface/src/former.rs
- protocols/fireface/src/former/ff400.rs
- protocols/fireface/src/former/ff800.rs
- protocols/fireface/src/latter.rs
- protocols/fireface/src/lib.rs
- runtime/fireface/src/ff400_model.rs
- runtime/fireface/src/former_ctls.rs
This patchset provides common interface to cache/update parameters specific to former models, including serializer/deserializer for the parameters..
```
Takashi Sakamoto (15):
protofols/fireface: add trait and its implementation for specification
in former models
protocols/fireface: implement trait to deserialize meter state in
former model
protocols/fireface: implement trait to cache meter state in former
models
runtime/fireface: use alternative way to cache meter state in former
models
protocols/fireface: implement trait to serialize/deserialize mixer
parameters in former models
protocols/fireface: implement trait to update mixer wholly in former
models
protocols/fireface: add trait to update the part of parameters after
comparing the content
protocols/fireface: implement trait to …
```
> [PATCH 00/15] protocols/fireface: implements traits to cache/update parameters specific to former models

- protocols/fireface/src/latter.rs
- protocols/fireface/src/latter/ff802.rs
- protocols/fireface/src/latter/ucx.rs
- runtime/fireface/src/latter_ctls.rs
This patchset provides implementations to cache/update parameters specific to latter models.
```
Takashi Sakamoto (16):
protocols/fireface: add trait to express specification of DSP in
latter model
protocols/fireface: implement traits to cache meter parameters in
latter models
runtime/fireface: use alternative way to cache meter parameters for
latter models
protocols/fireface: rename trait to express specification of DSP for
latter models
protocols/fireface: implement trait to update input parameters for
latter models
runtime/fireface: use alternative way to update input parameters for
latter models
protocols/fireface: implement trait to update output parameters for
latter models
runtime/fireface: use alternative way to update output parameters for
latter models
protocols/fireface: …
```
> [PATCH 00/16] protocols/fireface: implements traits to cache/update parameters specific to latter models

- protocols/fireworks/src/flash.rs
- protocols/fireworks/src/hw_ctl.rs
- protocols/fireworks/src/hw_info.rs
- protocols/fireworks/src/lib.rs
- protocols/fireworks/src/monitor.rs
- protocols/fireworks/src/phys_input.rs
- protocols/fireworks/src/phys_output.rs
- protocols/fireworks/src/playback.rs
- protocols/fireworks/src/port_conf.rs
- protocols/fireworks/src/robot_guitar.rs
- protocols/fireworks/src/transaction.rs
- runtime/fireworks/src/bin/snd-fireworks-ctl-service.rs
- runtime/fireworks/src/clk_ctl.rs
- runtime/fireworks/src/guitar_ctl.rs
- runtime/fireworks/src/iec60958_ctl.rs
- runtime/fireworks/src/input_ctl.rs
- runtime/fireworks/src/lib.rs
- runtime/fireworks/src/mixer_ctl.rs
- runtime/fireworks/src/model.rs
- runtime/fireworks/src/output_ctl.rs
- runtime/fireworks/src/port_ctl.rs
Current implementation uses ad-hoc parameter expression between protocols and runtime crates. It is too convenient to refactor traits in protocols crate.
This commit adds some intermediate expression for them.
```
Takashi Sakamoto (12):
runtime/fireworks: cache hardware information retrieved from the
target device
protocols/fireworks: add intermediate expression to cache sampling
clock configuration
protocols/fireworks: add intermediate expression to cache control room
source
protocols/fireworks: use intermediate expression to cache mode of
digital input and output
protocols/fireworks: add intermediate expression to cache phantom
powering configuration
protocols/fireworks: add intermediate expression to cache stream
mapping configuration
protocols/fireworks: add intermediate expression to …
```
> [PATCH 00/12] protocols/firewirks: use intermediate expression for parameters between protocols/runtime crates

- protocols/fireworks/src/audiofire.rs
- protocols/fireworks/src/flash.rs
- protocols/fireworks/src/hw_ctl.rs
- protocols/fireworks/src/hw_info.rs
- protocols/fireworks/src/lib.rs
- protocols/fireworks/src/monitor.rs
- protocols/fireworks/src/onyx_f.rs
- protocols/fireworks/src/phys_input.rs
- protocols/fireworks/src/phys_output.rs
- protocols/fireworks/src/playback.rs
- protocols/fireworks/src/port_conf.rs
- protocols/fireworks/src/rip.rs
- protocols/fireworks/src/robot_guitar.rs
- protocols/fireworks/src/transport.rs
- runtime/fireworks/src/lib.rs
- runtime/fireworks/src/port_ctl.rs
Current implementation has ad-hoc implementations for control operations, while it is not necessarily convenient in a point of code maintenance, especially for the case that the device includes out-of-specification behaviour.
This patchset introduces a trait to express hardware specification, then implements the
trait for each model. Some trait is added for cache and update operation for hardware
parameters, and they are implemented for operations. They are planned to be used for future work.
```
Takashi Sakamoto (21):
protocols/fireworks: add trait and its implementation to express
hardware specification
protocols/fireworks: add some trait to cache and update parameters
protocols/fireworks: implement cache trait for hardware information
protocols/fireworks: implement cache trait for …
```
> [PATCH 00/21] protocols/fireworks: add traits and their implementations for operations by unified way

- README.rst
- protocols/digi00x/src/lib.rs
- runtime/digi00x/Cargo.toml
- runtime/digi00x/src/bin/snd-firewire-digi00x-ctl-service.rs
- runtime/digi00x/src/lib.rs
- runtime/digi00x/src/model.rs
The main purpose of the patchset is to support debug logging by tracing crate
in runtime crate as the other service programs support, while protocols crate is
reworked for unified way to cache and update parameters.
```
Takashi Sakamoto (17):
protocols/digi00x: add intermediate expression for parameters
protocols/digi00x: add a trait to express hardware specification
protocols/digi00x: add a trait for hardware operation
protocols/digi00x: implement trait to cache and update source of
sampling clock
protocols/digi00x: implement trait to cache and update rate of media
clock
protocols/digi00x: implement trait to cache and update mode of optical
interface
protocols/digi00x: implement trait to detect source of external
sampling clock
protocols/digi00x: implement trait to cache and update …
```
> [PATCH 00/17] digi00x: support debug logging by tracing crate

- protocols/tascam/src/asynch.rs
- protocols/tascam/src/bin/tascam-hardware-info.rs
- protocols/tascam/src/isoch.rs
- runtime/tascam/src/fw1082_model.rs
- runtime/tascam/src/fw1804_model.rs
- runtime/tascam/src/fw1884_model.rs
- runtime/tascam/src/isoch_ctls.rs
- runtime/tascam/src/lib.rs
Current implementation of runtime crate uses the combination of structure and trait
implementation. It is necessarily useful since it can be rewritten by generic structure
with phantom data. This patchset reworks for the controls.
```
Takashi Sakamoto (9):
protocols/tascam: code cleanup by standard format
runtime/tascam: add generic structure of controls for sampling and
media clocks
runtime/tascam: add generic structure of controls for input signal
detection
runtime/tascam: add generic structure of controls for coaxial output
runtime/tascam: add generic structure of controls for optical
interfaces
runtime/tascam: add generic structure of controls for rack inputs
runtime/tascam: code refactoring for controls specific to FW-1884
runtime/tascam: add generic structure of controls for …
```
> [PATCH 0/9] runtime/tascam: use generic structure for controls

- protocols/tascam/src/asynch.rs
- protocols/tascam/src/asynch/fe8.rs
- protocols/tascam/src/isoch.rs
- protocols/tascam/src/isoch/fw1082.rs
- protocols/tascam/src/isoch/fw1804.rs
- protocols/tascam/src/isoch/fw1884.rs
- protocols/tascam/src/lib.rs
- runtime/tascam/src/fe8_model.rs
- runtime/tascam/src/fw1082_model.rs
- runtime/tascam/src/fw1804_model.rs
- runtime/tascam/src/fw1884_model.rs
- runtime/tascam/src/isoch_console_runtime.rs
- runtime/tascam/src/isoch_ctls.rs
- runtime/tascam/src/isoch_rack_runtime.rs
Current implementation has ad-hoc implementations for control operations, while it is not necessarily convenient in a point of code maintenance, especially for the case that the device includes out-of-specification behaviour.
This patchset introduces a trait to express hardware specification, then implements the
trait for each model. Some trait is added for cache and update operation for hardware
parameters, and they are implemented for operations.
```
Takashi Sakamoto (12):
runtime/tascam: add model-level cache function splitted from load
function
protocols/tascam: add traits to cache and update parameters for isoch
models
protocols/tascam: implement traits to cache and update parameters of
sampling and media clocks
protocols/tascam: implement traits to cache and update parameters of …
```
> [PATCH 00/12] protocols/tascam: add traits to cache and update parameters

- README.rst
- runtime/tascam/Cargo.toml
- runtime/tascam/src/bin/snd-firewire-tascam-ctl-service.rs
- runtime/tascam/src/fw1884_model.rs
- runtime/tascam/src/isoch_console_runtime.rs
- runtime/tascam/src/isoch_ctls.rs
- runtime/tascam/src/isoch_rack_runtime.rs
- runtime/tascam/src/lib.rs
It's really helpful to dump logs for debugging purpose. This patchset utilizes
tracing and tracing-subscriber crates for the purpose. An option is newly added
to fireworks runtime, then implement tracing events.
```
runtime/tascam: use tracing-subscriber crate to dump debug logs
runtime/tascam: add tracing span and event to runtime structure for
console model
runtime/tascam: add tracing span and event to runtime structure for
rack model
runtime/tascam: add tracing events for clock controls
runtime/tascam: add tracing events for input detection controls
runtime/tascam: add tracing events for coaxial output parameters
runtime/tascam: add tracing events for optical interface controls
runtime/tascam: add tracing events for rack input controls
runtime/tascam: add tracing …
```
> [PATCH 00/10] runtime/tascam: support debug logging by tracing crate

- protocols/motu/src/lib.rs
- protocols/motu/src/register_dsp.rs
- runtime/motu/src/audioexpress.rs
- runtime/motu/src/command_dsp_ctls.rs
- runtime/motu/src/command_dsp_runtime.rs
- runtime/motu/src/common_ctls.rs
- runtime/motu/src/f828.rs
- runtime/motu/src/f828mk2.rs
- runtime/motu/src/f828mk3.rs
- runtime/motu/src/f828mk3_hybrid.rs
- runtime/motu/src/f896.rs
- runtime/motu/src/f896hd.rs
- runtime/motu/src/f8pre.rs
- runtime/motu/src/h4pre.rs
- runtime/motu/src/lib.rs
- runtime/motu/src/register_dsp_ctls.rs
- runtime/motu/src/register_dsp_runtime.rs
- runtime/motu/src/track16.rs
- runtime/motu/src/traveler.rs
- runtime/motu/src/traveler_mk3.rs
- runtime/motu/src/ultralite.rs
- runtime/motu/src/ultralite_mk3.rs
- runtime/motu/src/ultralite_mk3_hybrid.rs
- runtime/motu/src/v1_ctls.rs
- runtime/motu/src/v1_runtime.rs
- runtime/motu/src/v2_ctls.rs
- runtime/motu/src/v3_ctls.rs
This patchset reworks current implementation of runtime for version 1 models so that
cache function is split from load function following to the other runtime implementations.
```
Takashi Sakamoto (8):
runtime/motu: code refactoring for use statements
runtime/motu: use generic structure for clock controls in version 1
models
runtime/motu: use generic structure for controls specific to version 1
models
runtime/motu: code refactoring for controls specific to 828
runtime/motu: use generic structure for word clock output controls
runtime/motu: use generic structure for AES/EBU converter controls
runtime/motu: use generic structure for level meter controls
runtime/motu: split cache function from load function in version 1
model
protocols/motu/src/lib.rs                |   5 +- …
```
> [PATCH 0/8] runtime/motu: rework for runtime of version 1 models

- protocols/motu/src/register_dsp.rs
- protocols/motu/src/version_2.rs
- runtime/motu/src/audioexpress.rs
- runtime/motu/src/common_ctls.rs
- runtime/motu/src/f828mk2.rs
- runtime/motu/src/f828mk3.rs
- runtime/motu/src/f828mk3_hybrid.rs
- runtime/motu/src/f896hd.rs
- runtime/motu/src/f8pre.rs
- runtime/motu/src/h4pre.rs
- runtime/motu/src/register_dsp_ctls.rs
- runtime/motu/src/register_dsp_runtime.rs
- runtime/motu/src/track16.rs
- runtime/motu/src/traveler.rs
- runtime/motu/src/traveler_mk3.rs
- runtime/motu/src/ultralite.rs
- runtime/motu/src/ultralite_mk3.rs
- runtime/motu/src/ultralite_mk3_hybrid.rs
- runtime/motu/src/v1_runtime.rs
- runtime/motu/src/v2_ctls.rs
- runtime/motu/src/v3_ctls.rs
This patchset reworks current implementation of runtime for Register DSP models so that
cache function is split from load function following to the other runtime implementations.
```
Takashi Sakamoto (17):
runtime/motu: use generic structure for controls specific to version 2
models
runtime/motu: use generic structure for optical interface controls
specific to version 2 model
runtime/motu: use generic structure for phone controls
runtime/motu: use generic structure for phone controls in Register DSP
models
runtime/motu: use generic structure for mixer return controls in
Register DSP models
runtime/motu: use generic structure for mixer output controls in
Register DSP models
runtime/motu: use generic structure for mixer monaural source control
in Register DSP models
runtime/motu: use …
```
> [PATCH 00/17] runtime/motu: rework for runtime of Register DSP models

- protocols/motu/src/command_dsp.rs
- runtime/motu/src/command_dsp_ctls.rs
- runtime/motu/src/command_dsp_runtime.rs
- runtime/motu/src/f828mk3.rs
- runtime/motu/src/f828mk3_hybrid.rs
- runtime/motu/src/register_dsp_runtime.rs
- runtime/motu/src/track16.rs
- runtime/motu/src/traveler_mk3.rs
- runtime/motu/src/ultralite_mk3.rs
- runtime/motu/src/ultralite_mk3_hybrid.rs
- runtime/motu/src/v3_ctls.rs
This patchset reworks current implementation of runtime for Command DSP models so that
cache function is split from load function following to the other runtime implementations.
```
Takashi Sakamoto (12):
runtime/motu: use generic structure for port assign controls in
version 3 models
runtime/motu: use generic structure for optical interface controls in
version 3 models
runtime/motu: use generic structure for reverb controls in Command DSP
models
runtime/motu: use generic structure for monitor controls in Command
DSP models
runtime/motu: use generic structure for mixer controls in Command DSP
models
runtime/motu: code refactoring for equalizer controls in Command DSP
models
runtime/motu: code refactoring for dynamics controls in Command DSP
models
runtime/motu: use generic structure for …
```
> [PATCH 00/12] runtime/motu: rework for runtime of Command DSP models

- README.rst
- runtime/motu/Cargo.toml
- runtime/motu/src/bin/snd-firewire-motu-ctl-service.rs
- runtime/motu/src/command_dsp_ctls.rs
- runtime/motu/src/command_dsp_runtime.rs
- runtime/motu/src/common_ctls.rs
- runtime/motu/src/f828.rs
- runtime/motu/src/lib.rs
- runtime/motu/src/register_dsp_ctls.rs
- runtime/motu/src/register_dsp_runtime.rs
- runtime/motu/src/traveler.rs
- runtime/motu/src/ultralite.rs
- runtime/motu/src/v1_ctls.rs
- runtime/motu/src/v1_runtime.rs
- runtime/motu/src/v2_ctls.rs
- runtime/motu/src/v3_ctls.rs
It's really helpful to dump logs for debugging purpose. This patchset utilizes
tracing and tracing-subscriber crates for the purpose. An option is newly added
to motu runtime, then implement tracing events.
```
Takashi Sakamoto (13):
runtime/motu: use tracing-subscriber crate to dump debug logs
runtime/motu: add tracing span and event to runtime for version 1
models
runtime/motu: add tracing span and event to runtime for Register DSP
models
runtime/motu: add tracing span and event to runtime for Command DSP
models
runtime/motu: add tracing event to common controls
runtime/motu: add tracing event to controls specific to version 1
models
runtime/motu: add tracing event to controls specific to version 2
models
runtime/motu: add tracing event to controls specific to version 3
models …
```
> [PATCH 00/13] runtime/motu: support debug logging by tracing crate

- protocols/motu/src/command_dsp.rs
- runtime/motu/src/command_dsp_ctls.rs
- runtime/motu/src/f828mk3_hybrid_model.rs
- runtime/motu/src/f828mk3_model.rs
- runtime/motu/src/track16_model.rs
- runtime/motu/src/traveler_mk3_model.rs
- runtime/motu/src/ultralite_mk3_hybrid_model.rs
- runtime/motu/src/ultralite_mk3_model.rs
The size of structures for input and output parameters is enough large since they
include equalizer and dynamics parameters. It brings overhead to operate them.
This patchset split equalizer and dynamcis parameters from them.
```
Takashi Sakamoto (5):
runtime/motu: fix invalid binding for protocol
protocols/motu: implement traits for input and output equalizer
parameters in Command DSP models
runtime/motu: use structures specific to equalizer effect parameters
in Command DSP models
protocols/motu: implement traits for input and output dynamics
parameters in Command DSP models
runtime/motu: use structures specific to dynamics effect parameters in
Command DSP models
protocols/motu/src/command_dsp.rs             | 512 +++++++++++-------
runtime/motu/src/command_dsp_ctls.rs          | 212 …
```
> [PATCH 0/5] protocols/motu: split equalizer/dynamics parameters from input/output parameters

- protocols/fireface/src/former.rs
- protocols/fireface/src/former/ff400.rs
- protocols/fireface/src/former/ff800.rs
- protocols/fireface/src/latter.rs
- protocols/fireface/src/latter/ff802.rs
- protocols/fireface/src/latter/ucx.rs
- protocols/fireface/src/lib.rs
- runtime/fireface/src/ff400_model.rs
- runtime/fireface/src/ff800_model.rs
- runtime/fireface/src/ff802_model.rs
- runtime/fireface/src/latter_ctls.rs
- runtime/fireface/src/lib.rs
- runtime/fireface/src/ucx_model.rs
Current implementation aggregates several parameters for latter models. It is
convenient, while forces runtime to duplicate larger parameters.
This patchset is to break down the aggregated parameters per each.
```
Takashi Sakamoto (17):
runtime/fireface: code refactoring for latter models
protocols/fireface: add serializer/deserializer specific to command
parameters in latter models
protocols/fireface: code refactoring for serializer/deserializer of
offset parameters in models
protocols/fireface: use generic trait implementation to operate
command parameters in latter models
runtime/fireface: isolate input parameters in latter models
runtime/fireface: isolate output parameters in latter models
runtime/fireface: isolate mixer parameters in latter models
runtime/fireface: isolate input and …
```
> [PATCH 00/17] protocols/fireface: break down parameters in latter models

- protocols/dice/src/tcelectronic/desktop.rs
- protocols/dice/src/tcelectronic/shell.rs
- protocols/dice/src/tcelectronic/shell/itwin.rs
- protocols/dice/src/tcelectronic/shell/k24d.rs
- protocols/dice/src/tcelectronic/shell/k8.rs
- protocols/dice/src/tcelectronic/shell/klive.rs
- protocols/dice/src/tcelectronic/studio.rs
- runtime/dice/src/tcelectronic.rs
- runtime/dice/src/tcelectronic/ch_strip_ctl.rs
- runtime/dice/src/tcelectronic/desktopk6_model.rs
- runtime/dice/src/tcelectronic/fw_led_ctl.rs
- runtime/dice/src/tcelectronic/itwin_model.rs
- runtime/dice/src/tcelectronic/k24d_model.rs
- runtime/dice/src/tcelectronic/k8_model.rs
- runtime/dice/src/tcelectronic/klive_model.rs
- runtime/dice/src/tcelectronic/midi_send_ctl.rs
- runtime/dice/src/tcelectronic/prog_ctl.rs
- runtime/dice/src/tcelectronic/reverb_ctl.rs
- runtime/dice/src/tcelectronic/shell_ctl.rs
- runtime/dice/src/tcelectronic/standalone_ctl.rs
- runtime/dice/src/tcelectronic/studiok48_model.rs
It is convenient for runtime implementation to use AsRef/AsMut trait implementations
since segment operation can be done transparently. This patchset is for the purpose.
```
Takashi Sakamoto (35):
runtime/dice: tcelectronic: code refactoring to dispatch arguments in
common trait implementation
protocols/dice: tcelectronic: implement AsRef/AsMut trait for state of
reverb effect
runtime/dice: tcelectronic: use generic structure for state of reverb
effect
protocols/dice: tcelectronic: implement AsRef/AsMut trait for meter of
reverb effect
runtime/dice: tcelectronic: use generic structure for meter of reverb
effect
protocols/dice: tcelectronic: implement AsRef/AsMut trait for state of
channel strip effect
runtime/dice: tcelectronic: use generic structure for state of channel
strip effect …
```
>  [PATCH 00/35] protocols/dice: tcelectronic: implement AsRef/AsMut to data of segment

- Cargo.toml
- README.rst
- protocols/dice/README.md
- protocols/dice/src/lib.rs
- protocols/dice/src/weiss.rs
- runtime/dice/src/main.rs
- runtime/dice/src/model.rs
- runtime/dice/src/weiss_model.rs
Hardware specification is provided by Weiss Engineering for some models. The series adds support for models from Weiss Engineering. At present, common functions are available.
```
Takashi Sakamoto (2):
protocols/dice: weiss: add support for Weiss Engineering models in common protocol
runtime/dice: weiss: add support for Weiss Engineering models
Cargo.toml                      |   4 +-
README.rst                      |  10 ++-
protocols/dice/README.md        |   8 +++
protocols/dice/src/lib.rs       |   1 +
protocols/dice/src/weiss.rs     |  89 ++++++++++++++++++++++++
runtime/dice/src/main.rs        |   1 +
runtime/dice/src/model.rs       |  99 ++++++++++++++++++++++++++-
runtime/dice/src/weiss_model.rs | 116 ++++++++++++++++++++++++++++++++
8 files changed, 324 insertions(+), 4 …
```
> [PATCH 0/2] dice: add support for Weiss Engineering models

- Cargo.toml
- README.rst
- protocols/motu/README.md
- protocols/motu/src/lib.rs
- protocols/motu/src/version_1.rs
- protocols/motu/src/version_2.rs
- protocols/motu/src/version_3.rs
- runtime/motu/src/command_dsp_runtime.rs
- runtime/motu/src/common_ctls.rs
- runtime/motu/src/f896mk3_hybrid_model.rs
- runtime/motu/src/f896mk3_model.rs
- runtime/motu/src/main.rs
Linux kernel v6.9 would support the models[1]. This series of changes adds support for the models in user space as well.
```
protocols/motu: start crate development for v0.3.0
protocols/motu: extend level meters specification to support for several type of digital inputs
protocols/motu: add support for MOTU 896 Mk3 models (both FireWire only and Hybrid models)
runtime/motu: add support for MOTU 896 mk3 models (both FireWire only and Hybrid models)
Cargo.toml                               |   4 +-
README.rst                               |  15 +-
protocols/motu/README.md                 |   2 +
protocols/motu/src/lib.rs                |  22 +-
protocols/motu/src/version_1.rs          |   8 +-
protocols/motu/src/version_2.rs          |   8 +- …
```
> protocols/motu: add support for 896 mk3 (both FireWire only and Hybrid models)

- Cargo.toml
- README.rst
- protocols/dice/Cargo.toml
- protocols/dice/README.md
- protocols/dice/src/bin/tcat-config-rom-parser.rs
- protocols/dice/src/lib.rs
- protocols/dice/src/tcat/config_rom.rs
- protocols/dice/src/tcelectronic.rs
- protocols/dice/src/weiss.rs
- protocols/dice/src/weiss/avc.rs
- protocols/dice/src/weiss/normal.rs
- runtime/dice/src/main.rs
- runtime/dice/src/model.rs
- runtime/dice/src/weiss.rs
- runtime/dice/src/weiss/avc.rs
- runtime/dice/src/weiss/normal.rs
The series of changes in this MR includes protocol implementation for the following models produced by Weiss Engieering.
* Weiss Engineering ADC2
* Weiss Engineering Vesta
* Weiss Engineering DAC2, Minerva
* Weiss Engineering AFI1
* Weiss Engineering INT202, INT203, DAC1 FireWire option card
* Weiss Engineering DAC202, Maya
* Weiss Engineering MAN301
The remarkable point is AV/C VENDOR-DEPENDENT command specific to TC Electronic. The command is used to configure MAN301. 
To @michele-perrone and @pirx08,
I posted a question about audio signal routing inner MAN301. I appreciate if getting your comments about it.
* https://lore.kernel.org/alsa-devel/20240121140748.GA189921@workstation.local/
> protocols/dice: weiss: add support for Weiss Engineering models

- protocols/bebob/Cargo.toml
- protocols/bebob/src/lib.rs
- protocols/dice/Cargo.toml
- protocols/dice/src/weiss/avc.rs
- protocols/digi00x/Cargo.toml
- protocols/fireface/Cargo.toml
- protocols/fireworks/Cargo.toml
- protocols/fireworks/src/transaction.rs
- protocols/motu/Cargo.toml
- protocols/motu/src/version_1.rs
- protocols/oxfw/Cargo.toml
- protocols/oxfw/src/lib.rs
- protocols/tascam/Cargo.toml
- protocols/tascam/src/asynch.rs
- runtime/bebob/Cargo.toml
- runtime/core/Cargo.toml
- runtime/core/src/dispatcher.rs
- runtime/dice/Cargo.toml
- runtime/digi00x/Cargo.toml
- runtime/fireface/Cargo.toml
- runtime/fireworks/Cargo.toml
- runtime/motu/Cargo.toml
- runtime/oxfw/Cargo.toml
- runtime/tascam/Cargo.toml
- runtime/tascam/src/main.rs
This commit switches the versions of dependent crates based on glib 0.19. This is the list of crates:
* glib crate 0.19
* hinawa crate 0.11
* hitaki crate 0.5
* alsactl crate 0.6
* alsaseq crate 0.6
```
Takashi Sakamoto (1):
Use crates based on glib 0.19
protocols/bebob/Cargo.toml             |  4 ++--
protocols/bebob/src/lib.rs             |  2 +-
protocols/dice/Cargo.toml              |  4 ++--
protocols/dice/src/weiss/avc.rs        |  2 +-
protocols/digi00x/Cargo.toml           |  4 ++--
protocols/fireface/Cargo.toml          |  4 ++--
protocols/fireworks/Cargo.toml         |  6 +++---
protocols/fireworks/src/transaction.rs |  1 +
protocols/motu/Cargo.toml              |  6 +++---
protocols/motu/src/version_1.rs        |  3 ++-
protocols/oxfw/Cargo.toml              |  4 ++-- …
```
> [PATCH 0/1] Use crates based on glib 0.19

- runtime/bebob/Cargo.toml
- runtime/bebob/src/main.rs
- runtime/core/Cargo.toml
- runtime/core/src/lib.rs
- runtime/dice/Cargo.toml
- runtime/dice/src/main.rs
- runtime/digi00x/Cargo.toml
- runtime/digi00x/src/main.rs
- runtime/fireface/Cargo.toml
- runtime/fireface/src/main.rs
- runtime/fireworks/Cargo.toml
- runtime/fireworks/src/main.rs
- runtime/motu/Cargo.toml
- runtime/motu/src/main.rs
- runtime/oxfw/Cargo.toml
- runtime/oxfw/src/main.rs
- runtime/tascam/Cargo.toml
- runtime/tascam/src/main.rs
This commit includes the changes to migrate to clap crate version 4.5.
> runtime: update clap crate version to v4.5

- README.rst
- protocols/bebob/Cargo.toml
- protocols/dice/Cargo.toml
- protocols/digi00x/Cargo.toml
- protocols/fireface/Cargo.toml
- protocols/fireworks/Cargo.toml
- protocols/motu/Cargo.toml
- protocols/oxfw/Cargo.toml
- protocols/tascam/Cargo.toml
- runtime/bebob/Cargo.toml
- runtime/core/Cargo.toml
- runtime/dice/Cargo.toml
- runtime/digi00x/Cargo.toml
- runtime/fireface/Cargo.toml
- runtime/fireworks/Cargo.toml
- runtime/motu/Cargo.toml
- runtime/oxfw/Cargo.toml
- runtime/tascam/Cargo.toml
The new release of gtk-rs stack was published in this July [1].
This commit changes the dependency on glib crate to version 0.20. MSRV is version 1.70.
[1] https://gtk-rs.org/blog/2024/07/17/new-release.html
> migrate to glib crate v0.20

- protocols/fireface/src/latter.rs
- runtime/fireface/src/latter_ctls.rs
The current implementation only allows setting eq gains between -2 and +2dB (should be between -20 and +20) , this PR fixes it.
> fireface: latter: fix eq gain range

- protocols/fireface/src/latter.rs
- protocols/fireface/src/latter/ff802.rs
- protocols/fireface/src/latter/ucx.rs
The controls for mixer stream source gains where inactive, and while fixing it I found out I needed to shift them by two channels to make them work as expected which I assumed was due to the 2 fx return channels, I may be wrong here but since the fx output are handled differently than the mixer gains I guess it's not so important.
> fireface: latter: inactive and shifted mixer stream source gain controls

- protocols/fireface/src/latter.rs
- runtime/fireface/src/latter_ctls.rs
Following up #194, I may be too naive here, but mixer gains do work perfectly between 32768 and 40960 and the dB scaling is consistent across the whole range so it seems safe to me to go on using integer arithmetics after all.
> fireface: latter: fix/workaround mixer gain scale

- runtime/fireface/src/latter_ctls.rs
This one is just a quality of life improvement for when using generic apps such as QasHCtl to check on meter values, the dB values where incorrect before.
> fireface: latter: fix meter db scale

- protocols/fireface/src/latter.rs
- runtime/fireface/src/latter_ctls.rs
The current default output volumes (+6dB) may produce saturation,  the usual 0dB seems a more sensible default value.
> fireface: latter: set default output volumes to 0dB instead of +6dB

- protocols/fireface/src/latter.rs
Here's another little fix for the latter RME's stereo output links ! Thanks for making this possible (not quite finished but getting there):
> fireface: latter: fix output stereo link and balance
